#:schema node_modules/wrangler/config-schema.json
name = "vinci"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "29aa07ec70434474932ce0f81466144e" }
]

[assets]
directory = "./public"
